<?php

// Fichier de langue anglaise
return [
    // gabarit.php
    // navigation
    "nav_home"=>"Home",
    "nav_contact"=>"Contact",
    "nav_connection"=>"Connection",
    "nav_register"=>"Register",
    "nav_disconnect"=>"Disconnect",
    "nav_searchHolder"=>"Search an offer",
    "nav_post_offers"=>"Post an offer",
    "nav_my_offers"=>"Manage my offers",
    // faq
    "faq_q1"=>"Can intergenerational, supportive cohabitation be achieved at any age?",
    "faq_a1"=>"The concept of intergenerational and supportive cohabitation is framed by the Loi Elan and stipulates that young people under 30 and people over 60, can do intergenerational cohabitation.<br><br>If you're over 30 and under 60, we invite you to visit 'La Carte des Colocs' or 'Cooloc'. They offer shared accommodation, rooms in private homes and room-sharing for all ages.",
    "faq_q2"=>"Can I register throughout the year?",
    "faq_a2"=>"Yes, of course. All you have to do is register your profile on our site - simply, free of charge and in just a few clicks. You can also create your profile now with a later availability or search date.",
    "faq_q3"=>"What does intergenerational cohabitation look like?",
    "faq_a3"=>"We draw up an intergenerational cohabitation contract, which is not a lease contract, but a charter for living well together, setting out all the organizational, relational and financial conditions established between each party. This contract entitles you to APL benefits as a student/young worker, and to tax exemption on the amounts received for the accommodation if you are over 60.",
    "faq_q4"=>"Can I host a young person if I'm a tenant?",
    "faq_a4"=>"Yes, we'll provide you with a letter to give to your landlord informing him or her that you're living with a young person, but your landlord can't object (unlike a sublet or shared flat).<br><br> Whether you are a tenant in a private, public or social housing scheme, the concept of intergenerational cohabitation is available to you.<br><br> Cf article L. 631-17 of the 2018 law on the evolution of housing, development and digital.",
    //foter
    "footer_nav"=>"Navigate",
    "footer_home"=>"Home",
    "footer_search"=>"Search an offer",
    "footer_contact"=>"Contact",
    "footer_connection"=>"Connection",
    "footer_register"=>"Register",
    "footer_legality"=>"Legality",
    "footer_legal"=>"Legal notice",
    "footer_cookies"=>"Cookies policy",
    "footer_terms"=>"Terms of use",
    "footer_socials"=>"Socials",
    "footer_rights"=>"© 2023 All rights reserved.",

    //vueContact.php
    "contact_title"=>"Contact Us",
    "contact_firstname"=>"Firstname",
    "contact_lastname"=>"Lastname",
    "contact_mail"=>"Email address",
    "contact_numHolder"=>"Format 0601020304",
    "contact_num"=>"Phone number <i>(optional)</i>",
    "contact_subjectHolder"=>"Subject of the message",
    "contact_subject"=>"Subject",
    "contact_message"=>"Message",
    "contact_send"=>"Send",

    // vueIndex.php
    "index_title"=>"Welcome to chezMamy, the first ethical platform for services between generations.",
    "index_presentation"=>"We connect seniors and students to promote the sharing of skills, experiences and mutual aid. Join us to be part of this great initiative!",
    "index_button1"=>"Looking for accommodation",
    "index_button2"=>"I have accommodation to offer",
    "index_pres_assoc_title"=>"Presentation of the association",
    "index_pres_assoc_subtitle"=>"Some figures",
    "index_pres_assoc_p1"=>"More than <span>1000</span> senior housing units available throughout France.",
    "index_pres_assoc_p2"=>"<span>75 %</span> of students reported an improvement in their mental well-being after living with a senior via our platform.",
    "index_pres_assoc_p3"=>"More than <span>5000</span> support services provided by students to our senior users each month.",
    "index_pres_assoc_p4"=>"A <span>50 %</span> increase in the feeling of security among seniors thanks to the presence of students.",
    "index_pres_assoc_p5"=>"More than <span>2000</span> hours of services provided by students in exchange for accommodation each week.",
    "index_pres_assoc_p6"=>"<span>80 %</span> of participating seniors reported being satisfied with the services provided by students.",
    "index_pres_assoc_p7"=>"<span>60 %</span> of students reported an improvement in their social and communication skills through interaction with seniors.",
    "index_pres_assoc_p8"=>"<span>20 %</span> reduction in housing costs for students participating in our exchange program.",
    "index_pres_assoc_p9"=>"More than <span>2000</span> pets cared for by volunteer students for senior users.",
    "index_pres_assoc_p10"=>"A <span>30 %</span> increase in the feeling of community among users thanks to intergenerational exchanges.",

    // vueConnexion.php
    "login_id"=>"Username",
    "login_password"=>"Password",
    "login_connect"=>"Log in",
    "login_no_account" => "I don't have an account, <a href='inscription'>create one</a>",

    // vueInscription.php
    "register_title" => "Profile Creation",
    "register_step" => "Step",
    "register_type_p" => "I am...",
    "register_type_student" => "Student looking for housing",
    "register_type_senior" => "Senior with a home to share",
    "register_prev_step" => "Previous step",
    "register_next_step" => "Next step",

    "register_yes" => "Yes",
    "register_no" => "No",

    // ---- partie étudiante ----
    "register_student_title" => "Student Profile",
    "register_student_category1" => "Identity",
    "register_student_firstname" => "First name",
    "register_student_lastname" => "Last name",
    "register_student_birthdate" => "Date of birth",
    "register_student_nationality" => "Nationality",
    "register_student_phone" => "Phone number",
    "register_student_phone_placeholder" => "In the format",
    "register_student_email" => "Email address",
    "register_student_city" => "City",
    "register_student_postal_code" => "Postal code",
    "register_student_postal_code_placeholder" => "Must be 5 digits",
    "register_student_know" => "How did you hear about chezMamy?",
    "register_student_motivations" => "Your motivations for choosing this housing mode",

    "register_student_category2" => "Studies / Internships",
    "register_student_domain" => "Field of study",
    "register_student_studies_lvl" => "Study level (targeted years of study)",
    "register_student_internships" => "Internships, specify",
    "register_student_internships_placeholder" => "No internships",
    "register_student_school" => "Educational institution",
    "register_student_years" => "Remaining years of study",
    "register_student_foreign" => "If you are new to our region, specify your arrival date",

    "register_student_category3" => "Getting to know you better",
    "register_student_smoker" => "Are you a smoker?",
    "register_student_allergy" => "Do you have any allergies?",
    "register_student_precise" => "Specify",
    "register_student_precise_placeholder" => "No allergies",
    "register_student_licence" => "Do you have a driver's license?",
    "register_student_locomotion" => "What is your means of transportation?",
    "register_student_interests" => "Your major interests",
    "register_student_why" => "Why do you want to live in intergenerational colocation?",

    "register_student_category4" => "Housing",
    "register_student_room_type" => "Type of room sought",
    "register_student_subcategory1" => "Details according to your choice of accommodation",
    "register_student_availability" => "Your availabilities",
    "register_student_begin" => "Start time",
    "register_student_end" => "End time",
    "register_student_budget" => "Your maximum budget for rent (in €)",

    "register_student_category5" => "Password and username",
    "register_student_login" => "Username",
    "register_student_password" => "Password",
    "register_student_password_repeat" => "Repeat password",
    "register_student_create" => "Create my student profile",

    // ---- partie senior ----
    "register_senior_title" => "Senior Profile",
    "register_senior_category1" => "Identity",
    "register_senior_firstname" => "First name",
    "register_senior_lastname" => "Last name",
    "register_senior_birthdate" => "Date of birth",
    "register_senior_living" => "I live...",
    "register_senior_city" => "City",
    "register_senior_postal_code" => "Postal code",
    "register_senior_postal_code_placeholder" => "Must be 5 digits",
    "register_senior_phone" => "Phone number",
    "register_senior_phone_placeholder" => "In the format",
    "register_senior_email" => "Email address",
    "register_senior_house_type" => "Type of accommodation",
    "register_senior_owner" => "I am...",
    "register_senior_pets" => "What pets do you have?",
    "register_senior_pets1" => "Dog",
    "register_senior_pets2" => "Cat",
    "register_senior_pets3" => "Ferret",
    "register_senior_pets4" => "Equines (horse, donkey)",
    "register_senior_pets5" => "Rodents (gerbil, chinchilla, guinea pig, hamster, degu, rat, rabbit, mouse, ...)",
    "register_senior_pets6" => "Sheep",
    "register_senior_pets7" => "Goat",
    "register_senior_pets8" => "Birds (finches, parakeets, parrots, chickens, quails, ducks, grouse, kiwi, ...)",
    "register_senior_pets9" => "Reptiles (snake, lizard, turtle, ...)",
    "register_senior_pets10" => "Fish",
    "register_senior_pets11" => "Insects",
    "register_senior_pets12" => "Others",
    "register_senior_smoker" => "Are you a smoker?",
    "register_senior_public_transport" => "Nearest public transport (distance in m)",
    "register_senior_know" => "How did you hear about chezMamy?",

    "register_senior_category2" => "Nature of services or presence",
    "register_senior_needs" => "What are your needs?",

    "register_senior_category3" => "Housing",
    "register_senior_room_type" => "Type of accommodation offered",
    "register_senior_summer" => "Can you accommodate a student during the summer holidays?",

    "register_senior_category4" => "Getting to know you better",
    "register_senior_interests" => "Your major interests",
    "register_senior_passion" => "What is your passion to share?",
    "register_senior_professional" => "What profession have you practiced?",
    "register_senior_why" => "Why do you want to live in intergenerational colocation with a student?",
    "register_senior_advantages" => "What advantage would a student have to live with you?",

    "register_senior_category5" => "Your entourage",
    "register_senior_kids" => "Do you have children?",
    "register_senior_grandkids" => "Do you have grandchildren?",
    "register_senior_family_presence" => "Is your family present in your daily life?",
    "register_senior_family_agreement" => "Does your family agree with your approach?",

    "register_senior_category6" => "Room characteristics",
    "register_senior_room_size" => "Area (in m²)",
    "register_senior_room_furnished" => "Is the room furnished?",
    "register_senior_room_equipment" => "Are there washing appliances?",
    "register_senior_internet" => "Is there internet?",

    "register_senior_category7" => "Password and username",
    "register_senior_login" => "Username",
    "register_senior_password" => "Password",
    "register_senior_password_repeat" => "Repeat password",
    "register_senior_create" => "Create my senior profile",

    // vuePosterOffres.php
    "offer_main_title" => "Post an offer",
    "offer_title" => "Offer title",
    "offer_housing" => "Type of housing",
    "offer_needs" => "What are your needs?",
    "offer_availability_dates" => "Housing availability dates",
    "offer_begin" => "Start date",
    "offer_end" => "End date",
    "offer_address" => "Address",
    "offer_surface" => "Room size (in m²)",
    "offer_description" => "Description",
    "offer_drop_files" => "Drop your pictures here",
    "offer_images" => "Images",
    "offer_submit" => "Submit offer",

    // vueChercherOffres.php
    "search_title" => "Search an offer",
    "offer_apply" => "Apply to offer",
    "no_offer" => "No offer found for your search.",

    // vueGererDemandesSenior.php
    "management_title" => "Manage your offers",
    "Name-and-surname" => "Name and surname : ",
    "Email-address" => "Email address : ",
    "Phone-number" => "Phone number : ",
];