<?php

// Fichier de langue française
return [
    "nav_home" => "Accueil",
    "nav_contact" => "Contact",
    "nav_connection" => "Connexion",
    "nav_register" => "Inscription",
    "nav_disconnect"=>"Déconnexion",
    "nav_searchHolder" => "Rechercher une offre",
    "faq_q1" => "La cohabitation intergénérationnelle et solidaire peut-elle être réalisée à n'importe quel âge ?",
    "faq_a1" => "Le concept de cohabitation intergénérationnelle et solidaire est encadré par la Loi Elan et stipule que les jeunes de moins de 30 ans et les personnes de plus de 60 ans peuvent cohabiter de manière intergénérationnelle.<br><br>Si vous avez plus de 30 ans et moins de 60 ans, nous vous invitons à visiter 'La Carte des Colocs' ou 'Cooloc'. Ils proposent des logements partagés, des chambres chez l'habitant et des colocations pour tous les âges.",
    "faq_q2" => "Puis-je m'inscrire tout au long de l'année ?",
    "faq_a2" => "Oui, bien sûr. Il vous suffit de vous inscrire sur notre site - simplement, gratuitement et en quelques clics. Vous pouvez également créer votre profil dès maintenant avec une disponibilité ultérieure ou une date de recherche.",
    "faq_q3" => "À quoi ressemble la cohabitation intergénérationnelle ?",
    "faq_a3" => "Nous établissons un contrat de cohabitation intergénérationnelle, qui n'est pas un contrat de bail, mais une charte pour bien vivre ensemble, définissant toutes les conditions organisationnelles, relationnelles et financières établies entre chaque partie. Ce contrat vous donne droit aux allocations de logement à caractère social en tant qu'étudiant/jeune travailleur, ainsi qu'à l'exonération fiscale sur les montants perçus pour le logement si vous avez plus de 60 ans.",
    "faq_q4" => "Puis-je héberger un jeune si je suis locataire ?",
    "faq_a4" => "Oui, nous vous fournirons une lettre à remettre à votre propriétaire pour l'informer que vous cohabitez avec un jeune, mais votre propriétaire ne peut pas s'y opposer (contrairement à une sous-location ou une colocation).<br><br>Que vous soyez locataire dans un logement privé, public ou social, le concept de cohabitation intergénérationnelle est disponible pour vous.<br><br> Cf article L. 631-17 de la loi de 2018 sur l'évolution du logement, de l'aménagement et du numérique.",
    "footer_nav" => "Navigation",
    "footer_home" => "Accueil",
    "footer_search" => "Rechercher une offre",
    "footer_contact" => "Contact",
    "footer_connection" => "Connexion",
    "footer_register" => "Inscription",
    "footer_legality" => "Légalité",
    "footer_legal" => "Mentions légales",
    "footer_cookies" => "Politique de cookies",
    "footer_terms" => "Conditions d'utilisation",
    "footer_socials" => "Réseaux sociaux",
    "footer_rights" => "© 2023 Tous droits réservés.",
    "register_id" => "Identifiant",
    "register_password" => "Mot de passe",
    "register_connect" => "Se connecter",
    "titre1_formulaire" => "Création de profil",
    "compteur_etape" => "Etape ",
    "formulaire_chois_compte" => "Je suis ...",
    "bouton_etudiant" => "Étudiant•e à la recherche d’un logement",
    "bouton_senior" => "Senior avec un logement à partager",
    "titre1_form_etudiant" => "Profil Eutdiant",
    "titre2_identite_etudiant" => "Identité",
    "formulaire_prenom_etudiant" => "Prénom",
    "formulaire_nom_etudiant" => "Nom",
    "formulaire_date_naissance_etudiant" => "Date de naissance",
    "formulaire_nationalite_etudiant" => "Nationalité",
    "formulaire_telephone_etudiant" => "Numéro de téléphone",
    "formulaire_email_etudiant" => "Adresse email",
    "formulaire_ville_etudiant" => "Ville",
    "formulaire_code_postal" => "Code postal",
    "title_input_postal_etudiant" => "Doit comporter 5 chiffres",
    "formulaire_notorieter_association_etudiant" => "Comment avez-vous connu notre association ?",
    "formulaire_motivation_etudiant" => "Vos motivations pour choisir ce mode de logement",

    "formulaire_bouton_precedent" => "Étape précédente",
    "formulaire_bouton_suivant" => "Étape suivante",

    "titre2_Etudes_stages" => "Etudes / stages",
    "formulaire_domaine_etude" => "Domaine d'étude",
    "formulaire_niveau_etude" => "Niveau d'étude (années d'études ciblées)",
    "formulaire_stage" => "Stages, préciser",
    "forumlaire_stage_placeholder" => "Aucun stage",
    "formulaire_etablissement" => "Etablissement d'enseignement",


];