<?php

// Fichier de langue française
return [
    // gabarit.php
    "nav_home" => "Accueil",
    "nav_contact" => "Contact",
    "nav_connection" => "Connexion",
    "nav_register" => "Inscription",
    "nav_disconnect"=>"Déconnexion",
    "nav_searchHolder" => "Rechercher une offre",
    "faq_q1" => "La cohabitation intergénérationnelle et solidaire peut-elle être réalisée à n'importe quel âge ?",
    "faq_a1" => "Le concept de cohabitation intergénérationnelle et solidaire est encadré par la Loi Elan et stipule que les jeunes de moins de 30 ans et les personnes de plus de 60 ans peuvent cohabiter de manière intergénérationnelle.<br><br>Si vous avez plus de 30 ans et moins de 60 ans, nous vous invitons à visiter 'La Carte des Colocs' ou 'Cooloc'. Ils proposent des logements partagés, des chambres chez l'habitant et des colocations pour tous les âges.",
    "faq_q2" => "Puis-je m'inscrire tout au long de l'année ?",
    "faq_a2" => "Oui, bien sûr. Il vous suffit de vous inscrire sur notre site - simplement, gratuitement et en quelques clics. Vous pouvez également créer votre profil dès maintenant avec une disponibilité ultérieure ou une date de recherche.",
    "faq_q3" => "À quoi ressemble la cohabitation intergénérationnelle ?",
    "faq_a3" => "Nous établissons un contrat de cohabitation intergénérationnelle, qui n'est pas un contrat de bail, mais une charte pour bien vivre ensemble, définissant toutes les conditions organisationnelles, relationnelles et financières établies entre chaque partie. Ce contrat vous donne droit aux allocations de logement à caractère social en tant qu'étudiant/jeune travailleur, ainsi qu'à l'exonération fiscale sur les montants perçus pour le logement si vous avez plus de 60 ans.",
    "faq_q4" => "Puis-je héberger un jeune si je suis locataire ?",
    "faq_a4" => "Oui, nous vous fournirons une lettre à remettre à votre propriétaire pour l'informer que vous cohabitez avec un jeune, mais votre propriétaire ne peut pas s'y opposer (contrairement à une sous-location ou une colocation).<br><br>Que vous soyez locataire dans un logement privé, public ou social, le concept de cohabitation intergénérationnelle est disponible pour vous.<br><br> Cf article L. 631-17 de la loi de 2018 sur l'évolution du logement, de l'aménagement et du numérique.",
    "footer_nav" => "Navigation",
    "footer_home" => "Accueil",
    "footer_search" => "Rechercher une offre",
    "footer_contact" => "Contact",
    "footer_connection" => "Connexion",
    "footer_register" => "Inscription",
    "footer_legality" => "Légalité",
    "footer_legal" => "Mentions légales",
    "footer_cookies" => "Politique de cookies",
    "footer_terms" => "Conditions d'utilisation",
    "footer_socials" => "Réseaux sociaux",
    "footer_rights" => "© 2023 Tous droits réservés.",

    //vueContact.php
    "contact_title"=>"Nous Contacter",
    "contact_firstname"=>"Prénom",
    "contact_lastname"=>"Nom",
    "contact_mail"=>"Adresse email",
    "contact_numHolder"=>"Au format 0601020304",
    "contact_num"=>"Numéro de téléphone <i>(facultatif)</i>",
    "contact_subjectHolder"=>"Sujet du message",
    "contact_subject"=>"Sujet",
    "contact_message"=>"Message",
    "contact_send"=>"Envoyer",

    // vueIndex.php
    "index_title" => "Bienvenue sur chezMamy, la première plateforme éthique de services entre générations.",
    "index_presentation" => "Nous connectons les seniors et les étudiants pour favoriser le partage de compétences, d'expériences et d'entraide. Rejoignez-nous pour faire partie de cette belle initiative !",
    "index_button1" => "Je cherche un logement",
    "index_button2" => "J'ai un logement à proposer",
    "index_pres_assoc_title" => "Présentation de l'association",
    "index_pres_assoc_subtitle" => "Quelques chiffres",
    "index_pres_assoc_p1" => "Plus de <span>1000</span> logements de séniors disponibles à travers toute la France.",
    "index_pres_assoc_p2" => "<span>75 %</span> des étudiants ont signalé une amélioration de leur bien-être mental après avoir vécu avec un senior via notre plateforme.",
    "index_pres_assoc_p3" => "Plus de <span>5000</span> services d'accompagnement rendus par des étudiants à nos utilisateurs séniors chaque mois.",
    "index_pres_assoc_p4" => "Une augmentation de <span>50 %</span> du sentiment de sécurité chez les séniors grâce à la présence des étudiants.",
    "index_pres_assoc_p5" => "Plus de <span>2000</span> heures de services rendus par les étudiants en échange d'un logement chaque semaine.",
    "index_pres_assoc_p6" => "<span>80 %</span> des séniors participants se sont déclarés satisfaits des services fournis par les étudiants.",
    "index_pres_assoc_p7" => "<span>60 %</span> des étudiants ont signalé une amélioration de leurs compétences sociales et de communication grâce à l'interaction avec les séniors.",
    "index_pres_assoc_p8" => "<span>20 %</span> de réduction des coûts de logement pour les étudiants qui participent à notre programme d'échange.",
    "index_pres_assoc_p9" => "Plus de <span>2000</span> animaux de compagnie pris en charge par des étudiants bénévoles pour les séniors utilisateurs.",
    "index_pres_assoc_p10" => "Une croissance de <span>30 %</span> du sentiment de communauté parmi les utilisateurs grâce aux échanges intergénérationnels.",

    // vueConnexion.php
    "login_id" => "Identifiant",
    "login_password" => "Mot de passe",
    "login_connect" => "Se connecter",

    // vueInscription.php
    "register_title" => "Création de profil",
    "register_step" => "Étape",
    "register_type_p" => "Je suis...",
    "register_type_student" => "Étudiant•e à la recherche d’un logement",
    "register_type_senior" => "Senior avec un logement à partager",
    "register_prev_step" => "Étape précédente",
    "register_next_step" => "Étape suivante",

    "register_yes" => "Oui",
    "register_no" => "Non",

    // ---- partie étudiante ----
    "register_student_title" => "Profil Étudiant•e",
    "register_student_category1" => "Identité",
    "register_student_firstname" => "Prénom",
    "register_student_lastname" => "Nom",
    "register_student_birthdate" => "Date de naissance",
    "register_student_nationality" => "Nationalité",
    "register_student_phone" => "Numéro de téléphone",
    "register_student_phone_placeholder" => "Au format",
    "register_student_email" => "Adresse e-mail",
    "register_student_city" => "Ville",
    "register_student_postal_code" => "Code postal",
    "register_student_postal_code_placeholder" => "Doit comporter 5 chiffres",
    "register_student_know" => "Comment avez-vous connu chezMamy ?",
    "register_student_motivations" => "Vos motivations pour choisir ce mode de logement",

    "register_student_category2" => "Études / Stages",
    "register_student_domain" => "Domaine d'études",
    "register_student_studies_lvl" => "Niveau d'étude (années d'études ciblées)",
    "register_student_internships" => "Stages, préciser",
    "register_student_internships_placeholder" => "Aucun stage",
    "register_student_school" => "Établissement d'enseignement",
    "register_student_years" => "Années d'études restantes",
    "register_student_foreign" => "Si vous êtes nouveau•elle venu•e dans notre région, précisez votre date d'arrivée",

    "register_student_category3" => "Mieux vous connaître",
    "register_student_smoker" => "Êtes-vous fumeur•se ?",
    "register_student_allergy" => "Avez-vous des allergies ?",
    "register_student_precise" => "Précisez",
    "register_student_precise_placeholder" => "Aucune allergie",
    "register_student_licence" => "Êtes-vous titulaire du permis de conduire ?",
    "register_student_locomotion" => "Quel est votre moyen de locomotion ?",
    "register_student_interests" => "Vos centres d'intérêt majeurs",
    "register_student_why" => "Pourquoi souhaitez-vous vivre en colocation intergénérationnelle ?",

    "register_student_category4" => "Logement",
    "register_student_room_type" => "Type de chambre recherchée",
    "register_student_subcategory1" => "Précisions selon votre choix de logement",
    "register_student_availability" => "Vos disponibilités",
    "register_student_begin" => "Heure de début",
    "register_student_end" => "Heure de fin",
    "register_student_budget" => "Votre budget maximum pour le loyer (en €)",

    "register_student_category5" => "Mot de passe et identifiant",
    "register_student_login" => "Identifiant",
    "register_student_password" => "Mot de passe",
    "register_student_password_repeat" => "Répétez le mot de passe",
    "register_student_create" => "Créer mon profil étudiant•e",

    // ---- partie senior ----
    "register_senior_title" => "Profil Senior",
    "register_senior_category1" => "Identité",
    "register_senior_firstname" => "Prénom",
    "register_senior_lastname" => "Nom",
    "register_senior_birthdate" => "Date de naissance",
    "register_senior_living" => "Je vis...",
    "register_senior_city" => "Ville",
    "register_senior_postal_code" => "Code postal",
    "register_senior_postal_code_placeholder" => "Doit comporter 5 chiffres",
    "register_senior_phone" => "Numéro de téléphone",
    "register_senior_phone_placeholder" => "Au format",
    "register_senior_email" => "Adresse e-mail",
    "register_senior_house_type" => "Type de logement",
    "register_senior_owner" => "Je suis...",
    "register_senior_pets" => "Quels animaux de compagnie avez-vous ?",
    "register_senior_pets1" => "Chien",
    "register_senior_pets2" => "Chat",
    "register_senior_pets3" => "Furet",
    "register_senior_pets4" => "Equins (cheval, âne)",
    "register_senior_pets5" => "Rongeurs (gerbille, chinchilla, cochon d’inde, hamster, octodon, rat, lapin, souris, …)",
    "register_senior_pets6" => "Mouton",
    "register_senior_pets7" => "Chèvre",
    "register_senior_pets8" => "Oiseaux (pinsons, perruche, perroquet, poule, caille, canard, tétras, kiwi, ...)",
    "register_senior_pets9" => "Reptiles (serpent, lézard, tortue, ...)",
    "register_senior_pets10" => "Poissons",
    "register_senior_pets11" => "Insectes",
    "register_senior_pets12" => "Autres",
    "register_senior_smoker" => "Êtes-vous fumeur•se ?",
    "register_senior_public_transport" => "Transports en commun les plus proches (distance en m)",
    "register_senior_know" => "Comment avez-vous connu chezMamy ?",

    "register_senior_category2" => "Nature des services ou présence",
    "register_senior_needs" => "Quels sont vos besoins ?",

    "register_senior_category3" => "Logement",
    "register_senior_room_type" => "Type de logement proposé",
    "register_senior_summer" => "Pouvez-vous accueillir un•e étudiant•e pendant les vacances d'été ?",

    "register_senior_category4" => "Mieux vous connaître",
    "register_senior_interests" => "Vos centres d'intérêt majeurs",
    "register_senior_passion" => "Quelle est votre passion à partager ?",
    "register_senior_professional" => "Quelle profession avez-vous exercé ?",
    "register_senior_why" => "Pourquoi souhaitez-vous vivre en colocation intergénérationnelle avec un•e étudiant•e ?",
    "register_senior_advantages" => "Quel avantage aurait un•e étudiant•e à cohabiter avec vous ?",

    "register_senior_category5" => "Votre entourage",
    "register_senior_kids" => "Avez-vous des enfants ?",
    "register_senior_grandkids" => "Avez-vous des petits-enfants ?",
    "register_senior_family_presence" => "Votre famille est-elle présente dans votre vie quotidienne ?",
    "register_senior_family_agreement" => "Votre famille est-elle d'accord avec votre démarche ?",

    "register_senior_category6" => "Caractéristiques de la chambre",
    "register_senior_room_size" => "Superficie (en m²)",
    "register_senior_room_furnished" => "La chambre est-elle meublée ?",
    "register_senior_room_equipment" => "Y'a-t-il des appareils pour lavage ?",
    "register_senior_internet" => "Y'a-t-il internet ?",

    "register_senior_category7" => "Mot de passe et identifiant",
    "register_senior_login" => "Identifiant",
    "register_senior_password" => "Mot de passe",
    "register_senior_password_repeat" => "Répétez le mot de passe",
    "register_senior_create" => "Créer mon profil senior"
];